name: Fuzz Testing

on:
  push:    # Trigger on every push to the repository
    branches:
      - main    # Run only on pushes to the main branch
      - '**'    # Include all branches if desired
  pull_request: # Trigger on pull requests as well
    branches:
      - main    # Run for pull requests targeting the main branch

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install pandas || echo "No dependencies to install"

    - name: Run fuzz testing
      run: python fuzz.py
